import fs from "fs";
import path from "path";
import { PREFIX } from "../../config.js";
import { isGroup } from "../../utils/index.js";

const dbPath = path.join(process.cwd(), "banco de dados", "rpg-usuarios.json");

export const ITENS_LOJA = {
  "1": { "nome": "Humano", "preco": 200, "tipo": "raca" },
  "2": { "nome": "Elfo", "preco": 200, "tipo": "raca" },
  "3": { "nome": "Oni (Demônio Oriental)", "preco": 200, "tipo": "raca" },
  "4": { "nome": "Meio-Fera", "preco": 200, "tipo": "raca" },
  "5": { "nome": "Anão", "preco": 200, "tipo": "raca" },
  "6": { "nome": "Morto-Vivo", "preco": 200, "tipo": "raca" },
  "7": { "nome": "Vampiro", "preco": 200, "tipo": "raca" },
  "8": { "nome": "Anjo Caído", "preco": 200, "tipo": "raca" },
  "9": { "nome": "Fada", "preco": 200, "tipo": "raca" },
  "10": { "nome": "Sereia / Tritão", "preco": 200, "tipo": "raca" },
  "11": { "nome": "Goblin", "preco": 200, "tipo": "raca" },
  "12": { "nome": "Orc", "preco": 200, "tipo": "raca" },
  "13": { "nome": "Ciborgue / Autômato", "preco": 200, "tipo": "raca" },
  "14": { "nome": "Espírito / Fantasma", "preco": 200, "tipo": "raca" },
  "15": { "nome": "Draconato (Meio-Dragão)", "preco": 200, "tipo": "raca" },
  "16": { "nome": "Elfo Negro (Drow)", "preco": 200, "tipo": "raca" },
  "17": { "nome": "Slime Humanóide", "preco": 200, "tipo": "raca" },
  "18": { "nome": "Metamorfo", "preco": 200, "tipo": "raca" },
  "19": { "nome": "Titã (Gigante)", "preco": 200, "tipo": "raca" },
  "20": { "nome": "Ser Estelar", "preco": 200, "tipo": "raca" },
  "21": { "nome": "Centauro", "preco": 250, "tipo": "raca" },
  "22": { "nome": "Minotauro", "preco": 250, "tipo": "raca" },
  "23": { "nome": "Lobisomem", "preco": 250, "tipo": "raca" },
  "24": { "nome": "Nefalim", "preco": 250, "tipo": "raca" },
  "25": { "nome": "Kitsune", "preco": 250, "tipo": "raca" },
  "26": { "nome": "Lizardfolk (Homem-Lagarto)", "preco": 250, "tipo": "raca" },
  "27": { "nome": "Gárgula", "preco": 250, "tipo": "raca" },
  "28": { "nome": "Sylph (Espírito do Ar)", "preco": 250, "tipo": "raca" },
  "29": { "nome": "Undine (Espírito da Água)", "preco": 250, "tipo": "raca" },
  "30": { "nome": "Salamandra (Espírito do Fogo)", "preco": 250, "tipo": "raca" },
  "31": { "nome": "Guerreiro", "preco": 200, "tipo": "classe" },
  "32": { "nome": "Mago", "preco": 200, "tipo": "classe" },
  "33": { "nome": "Assassino", "preco": 200, "tipo": "classe" },
  "34": { "nome": "Arqueiro", "preco": 200, "tipo": "classe" },
  "35": { "nome": "Samurai", "preco": 200, "tipo": "classe" },
  "36": { "nome": "Sacerdote / Clérigo", "preco": 200, "tipo": "classe" },
  "37": { "nome": "Paladino", "preco": 200, "tipo": "classe" },
  "38": { "nome": "Necromante", "preco": 200, "tipo": "classe" },
  "39": { "nome": "Ninja", "preco": 200, "tipo": "classe" },
  "40": { "nome": "Ladino / Larápio", "preco": 200, "tipo": "classe" },
  "41": { "nome": "Bardo", "preco": 200, "tipo": "classe" },
  "42": { "nome": "Bárbaro", "preco": 200, "tipo": "classe" },
  "43": { "nome": "Monge", "preco": 200, "tipo": "classe" },
  "44": { "nome": "Alquimista", "preco": 200, "tipo": "classe" },
  "45": { "nome": "Cavaleiro Rúnico", "preco": 200, "tipo": "classe" },
  "46": { "nome": "Druida", "preco": 200, "tipo": "classe" },
  "47": { "nome": "Lanceiro", "preco": 200, "tipo": "classe" },
  "48": { "nome": "Invocador (Summoner)", "preco": 200, "tipo": "classe" },
  "49": { "nome": "Atirador de Elite (Sniper)", "preco": 200, "tipo": "classe" },
  "50": { "nome": "Berserker", "preco": 200, "tipo": "classe" },
  "51": { "nome": "Cavaleiro da Morte", "preco": 200, "tipo": "classe" },
  "52": { "nome": "Bruxo", "preco": 200, "tipo": "classe" },
  "53": { "nome": "Feiticeiro", "preco": 200, "tipo": "classe" },
  "54": { "nome": "Caçador de Recompensas", "preco": 200, "tipo": "classe" },
  "55": { "nome": "Pirata", "preco": 200, "tipo": "classe" },
  "56": { "nome": "Mosqueteiro", "preco": 200, "tipo": "classe" },
  "57": { "nome": "Espadachim", "preco": 200, "tipo": "classe" },
  "58": { "nome": "Xamã", "preco": 200, "tipo": "classe" },
  "59": { "nome": "Domador de Feras", "preco": 200, "tipo": "classe" },
  "60": { "nome": "Ilusionista", "preco": 200, "tipo": "classe" },
  "61": { "nome": "Cavaleiro Sagrado", "preco": 200, "tipo": "classe" },
  "62": { "nome": "Guardião da Floresta", "preco": 200, "tipo": "classe" },
  "63": { "nome": "Pugilista", "preco": 200, "tipo": "classe" },
  "64": { "nome": "Mestre de Armas", "preco": 200, "tipo": "classe" },
  "65": { "nome": "Clérigo Sombrio", "preco": 200, "tipo": "classe" },
  "66": { "nome": "Geomante", "preco": 200, "tipo": "classe" },
  "67": { "nome": "Pirotecnista", "preco": 200, "tipo": "classe" },
  "68": { "nome": "Cronomante", "preco": 200, "tipo": "classe" },
  "69": { "nome": "Inquisidor", "preco": 200, "tipo": "classe" },
  "70": { "nome": "Algoz", "preco": 200, "tipo": "classe" },
  "71": { "nome": "🌸 Guardião de Sakura", "preco": 150, "tipo": "titulo" },
  "72": { "nome": "⚔️ Andarilho das Sombras", "preco": 150, "tipo": "titulo" },
  "73": { "nome": "🔥 Arauto do Cataclismo", "preco": 150, "tipo": "titulo" },
  "74": { "nome": "👑 Soberano da Taverna", "preco": 150, "tipo": "titulo" },
  "75": { "nome": "🌟 Herói Lendário", "preco": 150, "tipo": "titulo" },
  "76": { "nome": "💀 Ceifador de Almas", "preco": 150, "tipo": "titulo" },
  "77": { "nome": "🏹 Olho de Águia", "preco": 150, "tipo": "titulo" },
  "78": { "nome": "🔮 Mestre do Arcano", "preco": 150, "tipo": "titulo" },
  "79": { "nome": "🛡️ Escudo Inabalável", "preco": 150, "tipo": "titulo" },
  "80": { "nome": "🌊 Dominador dos Mares", "preco": 150, "tipo": "titulo" },
  "81": { "nome": "⚡ Veloz como o Relâmpago", "preco": 150, "tipo": "titulo" },
  "82": { "nome": "🌋 Coração de Lava", "preco": 150, "tipo": "titulo" },
  "83": { "nome": "🍃 Caminhante do Vento", "preco": 150, "tipo": "titulo" },
  "84": { "nome": "💎 Magnata do Reino", "preco": 150, "tipo": "titulo" },
  "85": { "nome": "🐺 Lobo Solitário", "preco": 150, "tipo": "titulo" },
  "86": { "nome": "🐉 Matador de Dragões", "preco": 150, "tipo": "titulo" },
  "87": { "nome": "🎭 Mestre do Disfarce", "preco": 150, "tipo": "titulo" },
  "88": { "nome": "😇 Anjo da Guarda", "preco": 150, "tipo": "titulo" },
  "89": { "nome": "👺 Demônio do Campo de Batalha", "preco": 150, "tipo": "titulo" },
  "90": { "nome": "🌌 Viajante do Cosmos", "preco": 150, "tipo": "titulo" },
  "91": { "nome": "🪙 Caçador de Tesouros", "preco": 150, "tipo": "titulo" },
  "92": { "nome": "🛠️ Ferreiro Lendário", "preco": 150, "tipo": "titulo" },
  "93": { "nome": "🩸 Sanguinário", "preco": 150, "tipo": "titulo" },
  "94": { "nome": "🌾 Protetor da Natureza", "preco": 150, "tipo": "titulo" },
  "95": { "nome": "🕯️ Iluminado", "preco": 150, "tipo": "titulo" },
  "96": { "nome": "📜 Sábio Ancestral", "preco": 150, "tipo": "titulo" },
  "97": { "nome": "💍 Senhor dos Anéis", "preco": 150, "tipo": "titulo" },
  "98": { "nome": "🍻 Rei da Cerveja", "preco": 150, "tipo": "titulo" },
  "99": { "nome": "🥊 Punhos de Aço", "preco": 150, "tipo": "titulo" },
  "100": { "nome": "💤 Dorminhoco", "preco": 150, "tipo": "titulo" },
  "101": { "nome": "🧊 Coração de Gelo", "preco": 150, "tipo": "titulo" },
  "102": { "nome": "✨ Brilho Estelar", "preco": 150, "tipo": "titulo" },
  "103": { "nome": "👁️ Olho que Tudo Vê", "preco": 150, "tipo": "titulo" },
  "104": { "nome": "🏜️ Nômade do Deserto", "preco": 150, "tipo": "titulo" },
  "105": { "nome": "🎪 Bobo da Corte", "preco": 150, "tipo": "titulo" },
  "106": { "nome": "🕸️ Viúva Negra", "preco": 150, "tipo": "titulo" },
  "107": { "nome": "⚓ Capitão dos Piratas", "preco": 150, "tipo": "titulo" },
  "108": { "nome": "🏰 Defensor do Castelo", "preco": 150, "tipo": "titulo" },
  "109": { "nome": "🦄 Domador de Unicórnios", "preco": 150, "tipo": "titulo" },
  "110": { "nome": "☀️ Cavaleiro da Luz", "preco": 150, "tipo": "titulo" },
  "111": { "nome": "🌙 Sombra da Lua", "preco": 150, "tipo": "titulo" },
  "112": { "nome": "🎰 Sortudo", "preco": 150, "tipo": "titulo" },
  "113": { "nome": "🃏 Trapaceiro", "preco": 150, "tipo": "titulo" },
  "114": { "nome": "🪓 Lenhador Supremo", "preco": 150, "tipo": "titulo" },
  "115": { "nome": "⛏️ Minerador de Elite", "preco": 150, "tipo": "titulo" },
  "116": { "nome": "🎣 Pescador de Monstros", "preco": 150, "tipo": "titulo" },
  "117": { "nome": "🦖 Caçador Pré-Histórico", "preco": 150, "tipo": "titulo" },
  "118": { "nome": "🛸 Forasteiro Espacial", "preco": 150, "tipo": "titulo" },
  "119": { "nome": "🦾 Indestrutível", "preco": 150, "tipo": "titulo" },
  "120": { "nome": "👻 Caça-Fantasmas", "preco": 150, "tipo": "titulo" },
  "121": { "nome": "Vassoura Voadora Mística", "preco": 800, "tipo": "montaria" },
  "122": { "nome": "Cavalo de Guerra Blindado", "preco": 800, "tipo": "montaria" },
  "123": { "nome": "Lobo Invernal Feroz", "preco": 800, "tipo": "montaria" },
  "124": { "nome": "Dragão Filhote de Rubi", "preco": 800, "tipo": "montaria" },
  "125": { "nome": "Grifo Imperial", "preco": 800, "tipo": "montaria" },
  "126": { "nome": "Tapete Mágico Ancestral", "preco": 800, "tipo": "montaria" },
  "127": { "nome": "Urso de Combate Blindado", "preco": 800, "tipo": "montaria" },
  "128": { "nome": "Tigre dente-de-sabre Elétrico", "preco": 800, "tipo": "montaria" },
  "129": { "nome": "Fênix de Fogo Renascida", "preco": 800, "tipo": "montaria" },
  "130": { "nome": "Pantera das Sombras", "preco": 800, "tipo": "montaria" },
  "131": { "nome": "Unicórnio Alado", "preco": 800, "tipo": "montaria" },
  "132": { "nome": "Pegaso Majestoso", "preco": 800, "tipo": "montaria" },
  "133": { "nome": "Cervo Sagrado da Floresta", "preco": 800, "tipo": "montaria" },
  "134": { "nome": "Javali Gigante Enfurecido", "preco": 800, "tipo": "montaria" },
  "135": { "nome": "Aranha Tecelã Gigante", "preco": 800, "tipo": "montaria" },
  "136": { "nome": "Escorpião do Deserto Rei", "preco": 800, "tipo": "montaria" },
  "137": { "nome": "Leão Dourado Real", "preco": 800, "tipo": "montaria" },
  "138": { "nome": "Carpete Voador de Seda", "preco": 800, "tipo": "montaria" },
  "139": { "nome": "Nuvem Voadora Kinton", "preco": 800, "tipo": "montaria" },
  "140": { "nome": "Manta Raia Celestial", "preco": 800, "tipo": "montaria" },
  "141": { "nome": "Tubartão Terrestre", "preco": 800, "tipo": "montaria" },
  "142": { "nome": "Tartaruga de Casco de Pedra", "preco": 800, "tipo": "montaria" },
  "143": { "nome": "Raposa de Nove Caudas", "preco": 800, "tipo": "montaria" },
  "144": { "nome": "Quimera de Guerra", "preco": 800, "tipo": "montaria" },
  "145": { "nome": "Mamute Lanudo Sela de Aço", "preco": 800, "tipo": "montaria" },
  "146": { "nome": "Avestruz de Corrida Veloz", "preco": 800, "tipo": "montaria" },
  "147": { "nome": "Camelo Real do Deserto", "preco": 800, "tipo": "montaria" },
  "148": { "nome": "Morcego Gigante Vampírico", "preco": 800, "tipo": "montaria" },
  "149": { "nome": "Hipogrifo Altivo", "preco": 800, "tipo": "montaria" },
  "150": { "nome": "Dragão Esquelético", "preco": 800, "tipo": "montaria" },
  "151": { "nome": "Caranguejo Gigante das Praias", "preco": 800, "tipo": "montaria" },
  "152": { "nome": "Gnu de Carga Reforçado", "preco": 800, "tipo": "montaria" },
  "153": { "nome": "Lama Cuspidadora de Fogo", "preco": 800, "tipo": "montaria" },
  "154": { "nome": "Gorgona de Montaria", "preco": 800, "tipo": "montaria" },
  "155": { "nome": "Golem de Pedra Portátil", "preco": 800, "tipo": "montaria" },
  "156": { "nome": "Salamandra Gigante", "preco": 800, "tipo": "montaria" },
  "157": { "nome": "Wyvern Verdejante", "preco": 800, "tipo": "montaria" },
  "158": { "nome": "Águia Gigante dos Picos", "preco": 800, "tipo": "montaria" },
  "159": { "nome": "Bode das Montanhas Saltador", "preco": 800, "tipo": "montaria" },
  "160": { "nome": "Mantícora Jovem", "preco": 800, "tipo": "montaria" },
  "161": { "nome": "Hidra Domada (Mini)", "preco": 800, "tipo": "montaria" },
  "162": { "nome": "Sapo Cururu Gigante Venenoso", "preco": 800, "tipo": "montaria" },
  "163": { "nome": "Besouro Chifrudo de Ferro", "preco": 800, "tipo": "montaria" },
  "164": { "nome": "Mula sem Cabeça Fantasmagórica", "preco": 800, "tipo": "montaria" },
  "165": { "nome": "Baleia Voadora Mística", "preco": 800, "tipo": "montaria" },
  "166": { "nome": "Gato Gigante de Botas", "preco": 800, "tipo": "montaria" },
  "167": { "nome": "Alpaca Mágica Arco-Íris", "preco": 800, "tipo": "montaria" },
  "168": { "nome": "Foca do Ártico Deslizante", "preco": 800, "tipo": "montaria" },
  "169": { "nome": "Panda Monge Sábio", "preco": 800, "tipo": "montaria" },
  "170": { "nome": "Hipopótamo de Armadura", "preco": 800, "tipo": "montaria" },
  "171": { "nome": "Rinoceronte de Chifre de Diamante", "preco": 800, "tipo": "montaria" },
  "172": { "nome": "Galo de Briga Gigante", "preco": 800, "tipo": "montaria" },
  "173": { "nome": "Pavão Majestoso de Cristal", "preco": 800, "tipo": "montaria" },
  "174": { "nome": "Búfalo Enfurecido", "preco": 800, "tipo": "montaria" },
  "175": { "nome": "Gafanhoto Saltador do Deserto", "preco": 800, "tipo": "montaria" },
  "176": { "nome": "Álvaro, o Carneiro Destemido", "preco": 800, "tipo": "montaria" },
  "177": { "nome": "Condor dos Andes Mutante", "preco": 800, "tipo": "montaria" },
  "178": { "nome": "Chocobo Amarelo", "preco": 800, "tipo": "montaria" },
  "179": { "nome": "Chocobo Preto Sombrio", "preco": 800, "tipo": "montaria" },
  "180": { "nome": "Chocobo Dourado Lendário", "preco": 800, "tipo": "montaria" },
  "181": { "nome": "Lagarto Monitor do Pântano", "preco": 800, "tipo": "montaria" },
  "182": { "nome": "Verme da Areia Miniatura", "preco": 800, "tipo": "montaria" },
  "183": { "nome": "Centopeia Gigante Huskar", "preco": 800, "tipo": "montaria" },
  "184": { "nome": "Besta do Caos Infernal", "preco": 800, "tipo": "montaria" },
  "185": { "nome": "Basilisco Petrificador", "preco": 800, "tipo": "montaria" },
  "186": { "nome": "Cérbero Filhote", "preco": 800, "tipo": "montaria" },
  "187": { "nome": "Pterodáctilo Mecânico", "preco": 800, "tipo": "montaria" },
  "188": { "nome": "T-Rex Domado com Sela", "preco": 800, "tipo": "montaria" },
  "189": { "nome": "Velociraptor Ágil", "preco": 800, "tipo": "montaria" },
  "190": { "nome": "Tricerátops Canhão de Assalto", "preco": 800, "tipo": "montaria" },
  "191": { "nome": "Cachorro Caramelo Lendário", "preco": 800, "tipo": "montaria" },
  "192": { "nome": "Capivara Suprema da Paz", "preco": 800, "tipo": "montaria" },
  "193": { "nome": "Boto Cor-de-Rosa Encantado", "preco": 800, "tipo": "montaria" },
  "194": { "nome": "Urso Polar de Gelo", "preco": 800, "tipo": "montaria" },
  "195": { "nome": "Besta Espiritual de Jade", "preco": 800, "tipo": "montaria" },
  "196": { "nome": "Foguete de Bolso Goblínico", "preco": 800, "tipo": "montaria" },
  "197": { "nome": "Submarino Steampunk de Bolso", "preco": 800, "tipo": "montaria" },
  "198": { "nome": "Disco Voador Alienígena", "preco": 800, "tipo": "montaria" },
  "199": { "nome": "Esfera de Energia Flutuante", "preco": 800, "tipo": "montaria" },
  "200": { "nome": "Vassoura de Limpeza Veloz", "preco": 800, "tipo": "montaria" },
  "201": { "nome": "Chapéu de Bruxo Estelar", "preco": 400, "tipo": "chapeu" },
  "202": { "nome": "Cartola do Nobre Corrompido", "preco": 400, "tipo": "chapeu" },
  "203": { "nome": "Capuz do Assassino da Névoa", "preco": 400, "tipo": "chapeu" },
  "204": { "nome": "Coroa do Rei Decaído", "preco": 400, "tipo": "chapeu" },
  "205": { "nome": "Yasa (Chapéu de Palha Samurai)", "preco": 400, "tipo": "chapeu" },
  "206": { "nome": "Boina do Detetive Arcano", "preco": 400, "tipo": "chapeu" },
  "207": { "nome": "Elmo do Cavaleiro de Sangue", "preco": 400, "tipo": "chapeu" },
  "208": { "nome": "Tiara da Princesa Élfica", "preco": 400, "tipo": "chapeu" },
  "209": { "nome": "Bandana do Pirata Caçador", "preco": 400, "tipo": "chapeu" },
  "210": { "nome": "Capacete de Mineração com Lanterna", "preco": 400, "tipo": "chapeu" },
  "211": { "nome": "Diadema do Conhecimento", "preco": 400, "tipo": "chapeu" },
  "212": { "nome": "Máscara de Gás Steampunk", "preco": 400, "tipo": "chapeu" },
  "213": { "nome": "Turbante do Sultão das Areias", "preco": 400, "tipo": "chapeu" },
  "214": { "nome": "Gorro de Natal Festivo", "preco": 400, "tipo": "chapeu" },
  "215": { "nome": "Orelhas de Coelho Fofinhas", "preco": 400, "tipo": "chapeu" },
  "216": { "nome": "Chifres de Demônio do Submundo", "preco": 400, "tipo": "chapeu" },
  "217": { "nome": "Auréola de Anjo Resplandecente", "preco": 400, "tipo": "chapeu" },
  "218": { "nome": "Capuz de Monge Caído", "preco": 400, "tipo": "chapeu" },
  "219": { "nome": "Chapéu de Cowboy do Velho Oeste", "preco": 400, "tipo": "chapeu" },
  "220": { "nome": "Máscara Kitsune Pintada", "preco": 400, "tipo": "chapeu" },
  "221": { "nome": "Elmo de Espartano Bronze", "preco": 400, "tipo": "chapeu" },
  "222": { "nome": "Máscara Tengu Vermelha", "preco": 400, "tipo": "chapeu" },
  "223": { "nome": "Coroa de Espinhos do Mártir", "preco": 400, "tipo": "chapeu" },
  "224": { "nome": "Chapéu de Caçador de Monsters", "preco": 400, "tipo": "chapeu" },
  "225": { "nome": "Capuz Alquímico Verde", "preco": 400, "tipo": "chapeu" },
  "226": { "nome": "Gorro de Lã do Alasca", "preco": 400, "tipo": "chapeu" },
  "227": { "nome": "Boina Militar de Elite", "preco": 400, "tipo": "chapeu" },
  "228": { "nome": "Máscara de Baile de Máscaras", "preco": 400, "tipo": "chapeu" },
  "229": { "nome": "Bandana da Aldeia da Folha", "preco": 400, "tipo": "chapeu" },
  "230": { "nome": "Elmo de Viking com Chifres", "preco": 400, "tipo": "chapeu" },
  "231": { "nome": "Capacete de Astronauta Retro", "preco": 400, "tipo": "chapeu" },
  "232": { "nome": "Tiara de Flores de Sakura", "preco": 400, "tipo": "chapeu" },
  "233": { "nome": "Chapéu de Mosqueteiro com Pena", "preco": 400, "tipo": "chapeu" },
  "234": { "nome": "Máscara do Fantasma da Ópera", "preco": 400, "tipo": "chapeu" },
  "235": { "nome": "Chifres de Cervo da Floresta", "preco": 400, "tipo": "chapeu" },
  "236": { "nome": "Orelhas de Gato Neko", "preco": 400, "tipo": "chapeu" },
  "237": { "nome": "Capuz de Cultista Sombrio", "preco": 400, "tipo": "chapeu" },
  "238": { "nome": "Elmo Gladiador de Aço", "preco": 400, "tipo": "chapeu" },
  "239": { "nome": "Coroa de Louros do Imperador", "preco": 400, "tipo": "chapeu" },
  "240": { "nome": "Chapéu de Palha do Pirata Que Estica", "preco": 400, "tipo": "chapeu" },
  "241": { "nome": "Máscara Cyberpunk de Neon", "preco": 400, "tipo": "chapeu" },
  "242": { "nome": "Gorro de Goblin Orelhudo", "preco": 400, "tipo": "chapeu" },
  "243": { "nome": "Tiara de Cristal de Gelo", "preco": 400, "tipo": "chapeu" },
  "244": { "nome": "Capuz do Espantalho Assombrado", "preco": 400, "tipo": "chapeu" },
  "245": { "nome": "Elmo do Dragão de Fogo", "preco": 400, "tipo": "chapeu" },
  "246": { "nome": "Chapéu de Confeiteiro Mágico", "preco": 400, "tipo": "chapeu" },
  "247": { "nome": "Máscara de Médico da Peste", "preco": 400, "tipo": "chapeu" },
  "248": { "nome": "Capacete Primitivo de Crânio", "preco": 400, "tipo": "chapeu" },
  "249": { "nome": "Boina de Artista Pintor", "preco": 400, "tipo": "chapeu" },
  "250": { "nome": "Cartola Steampunk de Latão", "preco": 400, "tipo": "chapeu" },
  "251": { "nome": "Bandana de Renegado", "preco": 400, "tipo": "chapeu" },
  "252": { "nome": "Chifres de Dragão Ancião", "preco": 400, "tipo": "chapeu" },
  "253": { "nome": "Auréola Negra Corrompida", "preco": 400, "tipo": "chapeu" },
  "254": { "nome": "Orelhas de Raposa de Fogo", "preco": 400, "tipo": "chapeu" },
  "255": { "nome": "Gorro de Bobo da Corte Colorido", "preco": 400, "tipo": "chapeu" },
  "256": { "nome": "Elmo de Paladino Iluminado", "preco": 400, "tipo": "chapeu" },
  "257": { "nome": "Capuz de Gatuno Furtivo", "preco": 400, "tipo": "chapeu" },
  "258": { "nome": "Máscara de Palhaço Macabro", "preco": 400, "tipo": "chapeu" },
  "259": { "nome": "Tiara da Lua Crescente", "preco": 400, "tipo": "chapeu" },
  "260": { "nome": "Coroa de Ouro Maciço", "preco": 400, "tipo": "chapeu" },
  "261": { "nome": "Chapéu de Explorador da Selva", "preco": 400, "tipo": "chapeu" },
  "262": { "nome": "Máscara de Oni Azul", "preco": 400, "tipo": "chapeu" },
  "263": { "nome": "Máscara de Oni Vermelho", "preco": 400, "tipo": "chapeu" },
  "264": { "nome": "Elmo Samurai Clássico", "preco": 400, "tipo": "chapeu" },
  "265": { "nome": "Capacete de Guarda Real", "preco": 400, "tipo": "chapeu" },
  "266": { "nome": "Gorro de Pirata com Caveira", "preco": 400, "tipo": "chapeu" },
  "267": { "nome": "Máscara de Hacker Anônimo", "preco": 400, "tipo": "chapeu" },
  "268": { "nome": "Tiara de Conchas do Mar", "preco": 400, "tipo": "chapeu" },
  "269": { "nome": "Chapéu de Pescador Velho", "preco": 400, "tipo": "chapeu" },
  "270": { "nome": "Boina de Marinheiro", "preco": 400, "tipo": "chapeu" },
  "271": { "nome": "Capuz de Tecromante Sombrio", "preco": 400, "tipo": "chapeu" },
  "272": { "nome": "Chifres de Touro Furioso", "preco": 400, "tipo": "chapeu" },
  "273": { "nome": "Orelhas de Lobo Feroz", "preco": 400, "tipo": "chapeu" },
  "274": { "nome": "Capacete de Samurai Futurista", "preco": 400, "tipo": "chapeu" },
  "275": { "nome": "Diadema de Esmeralda Mística", "preco": 400, "tipo": "chapeu" },
  "276": { "nome": "Coroa de Gelo do Lich", "preco": 400, "tipo": "chapeu" },
  "277": { "nome": "Chapéu de Alquimista Supremo", "preco": 400, "tipo": "chapeu" },
  "278": { "nome": "Máscara de Abóbora de Halloween", "preco": 400, "tipo": "chapeu" },
  "279": { "nome": "Elmo de Cavaleiro Rúnico", "preco": 400, "tipo": "chapeu" },
  "280": { "nome": "Gorro de Elfo Ajudante", "preco": 400, "tipo": "chapeu" },
  "281": { "nome": "Anel do Lorde Vampiro", "preco": 500, "tipo": "acessorio" },
  "282": { "nome": "Amuleto de Olho de Dragão", "preco": 500, "tipo": "acessorio" },
  "283": { "nome": "Capa da Invisibilidade Parcial", "preco": 500, "tipo": "acessorio" },
  "284": { "nome": "Brincos de Cristal de Mana", "preco": 500, "tipo": "acessorio" },
  "285": { "nome": "Luvas do Alquimista Pródigo", "preco": 500, "tipo": "acessorio" },
  "286": { "nome": "Colar de Dente de Tubarão", "preco": 500, "tipo": "acessorio" },
  "287": { "nome": "Bracelete de Ouro de Cleópatra", "preco": 500, "tipo": "acessorio" },
  "288": { "nome": "Anel da Sorte Infinita", "preco": 500, "tipo": "acessorio" },
  "289": { "nome": "Amuleto do Coração da Floresta", "preco": 500, "tipo": "acessorio" },
  "290": { "nome": "Capa do Vento Veloz", "preco": 500, "tipo": "acessorio" },
  "291": { "nome": "Luvas de Couro de Dragão", "preco": 500, "tipo": "acessorio" },
  "292": { "nome": "Cinto de Utilidades do Ladino", "preco": 500, "tipo": "acessorio" },
  "293": { "nome": "Brincos de Esmeralda Celestial", "preco": 500, "tipo": "acessorio" },
  "294": { "nome": "Colar de Lágrima de Sereia", "preco": 500, "tipo": "acessorio" },
  "295": { "nome": "Anel de Fogo do Submundo", "preco": 500, "tipo": "acessorio" },
  "296": { "nome": "Amuleto de Proteção Divina", "preco": 500, "tipo": "acessorio" },
  "297": { "nome": "Capa de Plumas de Fênix", "preco": 500, "tipo": "acessorio" },
  "298": { "nome": "Luvas de Ferro do Titã", "preco": 500, "tipo": "acessorio" },
  "299": { "nome": "Cinto de Força do Gigante", "preco": 500, "tipo": "acessorio" },
  "300": { "nome": "Brincos de Rubi Sangrento", "preco": 500, "tipo": "acessorio" },
  "301": { "nome": "Colar de runas Antigas", "preco": 500, "tipo": "acessorio" },
  "302": { "nome": "Anel de Invisibilidade Temporária", "preco": 500, "tipo": "acessorio" },
  "303": { "nome": "Amuleto do Sol Nascente", "preco": 500, "tipo": "acessorio" },
  "304": { "nome": "Capa de Sombras Furtivas", "preco": 500, "tipo": "acessorio" },
  "305": { "nome": "Luvas de Seda Mágica", "preco": 500, "tipo": "acessorio" },
  "306": { "nome": "Cinto de Gravidade Zero", "preco": 500, "tipo": "acessorio" },
  "307": { "nome": "Brincos de Safira Estelar", "preco": 500, "tipo": "acessorio" },
  "308": { "nome": "Colar de Ossos de Dragão", "preco": 500, "tipo": "acessorio" },
  "309": { "nome": "Anel do Rei Salomão", "preco": 500, "tipo": "acessorio" },
  "310": { "nome": "Amuleto da Noite Eterna", "preco": 500, "tipo": "acessorio" },
  "311": { "nome": "Capa da Tempestade Elétrica", "preco": 500, "tipo": "acessorio" },
  "312": { "nome": "Luvas do Arqueiro de Elite", "preco": 500, "tipo": "acessorio" },
  "313": { "nome": "Cinto de Armazenamento Infinito", "preco": 500, "tipo": "acessorio" },
  "314": { "nome": "Brincos de Pérola Negra", "preco": 500, "tipo": "acessorio" },
  "315": { "nome": "Colar de Pingente de Espada", "preco": 500, "tipo": "acessorio" },
  "316": { "nome": "Anel de Gelo Eterno", "preco": 500, "tipo": "acessorio" },
  "317": { "nome": "Amuleto do Olho que Tudo Vê", "preco": 500, "tipo": "acessorio" },
  "318": { "nome": "Capa do Rei Decaído", "preco": 500, "tipo": "acessorio" },
  "319": { "nome": "Luvas de Combate de Boxer", "preco": 500, "tipo": "acessorio" },
  "320": { "nome": "Cinto de Fivelas Steampunk", "preco": 500, "tipo": "acessorio" },
  "321": { "nome": "Brincos de Quartzo Rosa", "preco": 500, "tipo": "acessorio" },
  "322": { "nome": "Colar de Medalhão Antigo", "preco": 500, "tipo": "acessorio" },
  "323": { "nome": "Anel de Ilusão Óptica", "preco": 500, "tipo": "acessorio" },
  "324": { "nome": "Amuleto do Tempo Estagnado", "preco": 500, "tipo": "acessorio" },
  "325": { "nome": "Capa de Asas de Morcego", "preco": 500, "tipo": "acessorio" },
  "326": { "nome": "Luvas de Garra de Gato", "preco": 500, "tipo": "acessorio" },
  "327": { "nome": "Cinto de Chamas Ardentes", "preco": 500, "tipo": "acessorio" },
  "328": { "nome": "Brincos de Diamante Puro", "preco": 500, "tipo": "acessorio" },
  "329": { "nome": "Colar de Corrente de Prata", "preco": 500, "tipo": "acessorio" },
  "330": { "nome": "Anel do Sacrifício", "preco": 500, "tipo": "acessorio" },
  "331": { "nome": "Amuleto da Fênix de Fogo", "preco": 500, "tipo": "acessorio" },
  "332": { "nome": "Capa de Pele de Lobo", "preco": 500, "tipo": "acessorio" },
  "333": { "nome": "Luvas de Proteção Térmica", "preco": 500, "tipo": "acessorio" },
  "334": { "nome": "Cinto Escudo de Força", "preco": 500, "tipo": "acessorio" },
  "335": { "nome": "Brincos de Âmbar Antigo", "preco": 500, "tipo": "acessorio" },
  "336": { "nome": "Colar de Presa de Lobo", "preco": 500, "tipo": "acessorio" },
  "337": { "nome": "Anel de Gravidade Aumentada", "preco": 500, "tipo": "acessorio" },
  "338": { "nome": "Amuleto de Mana Infinito", "preco": 500, "tipo": "acessorio" },
  "339": { "nome": "Capa do Mago Supremo", "preco": 500, "tipo": "acessorio" },
  "340": { "nome": "Luvas do Mestre Maçom", "preco": 500, "tipo": "acessorio" },
  "341": { "nome": "Cinto de Cavaleiro Sagrado", "preco": 500, "tipo": "acessorio" },
  "342": { "nome": "Brincos de Jade Mística", "preco": 500, "tipo": "acessorio" },
  "343": { "nome": "Colar de Pingente de Cruz", "preco": 500, "tipo": "acessorio" },
  "344": { "nome": "Anel de Casamento Amaldiçoado", "preco": 500, "tipo": "acessorio" },
  "345": { "nome": "Amuleto de Sangue Vampírico", "preco": 500, "tipo": "acessorio" },
  "346": { "nome": "Capa do Executor de Almas", "preco": 500, "tipo": "acessorio" },
  "347": { "nome": "Luvas de Toque Macabro", "preco": 500, "tipo": "acessorio" },
  "348": { "nome": "Cinto Espinhoso", "preco": 500, "tipo": "acessorio" },
  "349": { "nome": "Brincos de Topázio Imperial", "preco": 500, "tipo": "acessorio" },
  "350": { "nome": "Colar de Pena de Grifo", "preco": 500, "tipo": "acessorio" },
  "351": { "nome": "Anel de Comunicação à Distância", "preco": 500, "tipo": "acessorio" },
  "352": { "nome": "Amuleto do Caos Profundo", "preco": 500, "tipo": "acessorio" },
  "353": { "nome": "Capa de Seda Estelar", "preco": 500, "tipo": "acessorio" },
  "354": { "nome": "Luvas Gravitacionais", "preco": 500, "tipo": "acessorio" },
  "355": { "nome": "Cinto de Moedas de Ouro", "preco": 500, "tipo": "acessorio" },
  "356": { "nome": "Brincos de Opala de Fogo", "preco": 500, "tipo": "acessorio" },
  "357": { "nome": "Colar de Pingente de Âncora", "preco": 500, "tipo": "acessorio" },
  "358": { "nome": "Anel da Destruição", "preco": 500, "tipo": "acessorio" },
  "359": { "nome": "Amuleto de Sorte do Gato", "preco": 500, "tipo": "acessorio" },
  "360": { "nome": "Capa de Tecido rúnico", "preco": 500, "tipo": "acessorio" },
  "361": { "nome": "Brisa de Sakura (Moldura)", "preco": 300, "tipo": "moldura" },
  "362": { "nome": "Chamas do Submundo (Moldura)", "preco": 300, "tipo": "moldura" },
  "363": { "nome": "Aura Divina (Moldura)", "preco": 300, "tipo": "moldura" },
  "364": { "nome": "Ciberpunk Neon (Moldura)", "preco": 300, "tipo": "moldura" },
  "365": { "nome": "Gelo Eterno (Moldura)", "preco": 300, "tipo": "moldura" },
  "366": { "nome": "Ouro Real Nobre (Moldura)", "preco": 300, "tipo": "moldura" },
  "367": { "nome": "Floresta Encantada (Moldura)", "preco": 300, "tipo": "moldura" },
  "368": { "nome": "Vampiro Sangrento (Moldura)", "preco": 300, "tipo": "moldura" },
  "369": { "nome": "Galáxia Estelar (Moldura)", "preco": 300, "tipo": "moldura" },
  "370": { "nome": "Pirata dos Mares (Moldura)", "preco": 300, "tipo": "moldura" },
  "371": { "nome": "Zumbi Decomposto (Moldura)", "preco": 300, "tipo": "moldura" },
  "372": { "nome": "Anjo de Luz (Moldura)", "preco": 300, "tipo": "moldura" },
  "373": { "nome": "Demônio de Chifres (Moldura)", "preco": 300, "tipo": "moldura" },
  "374": { "nome": "Samurai de Aço (Moldura)", "preco": 300, "tipo": "moldura" },
  "375": { "nome": "Ninja Furtivo (Moldura)", "preco": 300, "tipo": "moldura" },
  "376": { "nome": "Mago Arcano (Moldura)", "preco": 300, "tipo": "moldura" },
  "377": { "nome": "Ferreiro de Ferro (Moldura)", "preco": 300, "tipo": "moldura" },
  "378": { "nome": "Alquimista Tóxico (Moldura)", "preco": 300, "tipo": "moldura" },
  "379": { "nome": "Steampunk Bronze (Moldura)", "preco": 300, "tipo": "moldura" },
  "380": { "nome": "Halloween Abóbora (Moldura)", "preco": 300, "tipo": "moldura" },
  "381": { "nome": "Natal Festivo (Moldura)", "preco": 300, "tipo": "moldura" },
  "382": { "nome": "Arco-Íris Mágico (Moldura)", "preco": 300, "tipo": "moldura" },
  "383": { "nome": "Deserto de Areia (Moldura)", "preco": 300, "tipo": "moldura" },
  "384": { "nome": "Oceano Profundo (Moldura)", "preco": 300, "tipo": "moldura" },
  "385": { "nome": "Vulcão em Erupção (Moldura)", "preco": 300, "tipo": "moldura" },
  "386": { "nome": "Relâmpago Tempestuoso (Moldura)", "preco": 300, "tipo": "moldura" },
  "387": { "nome": "Sombras Sombrias (Moldura)", "preco": 300, "tipo": "moldura" },
  "388": { "nome": "Luz Sagrada (Moldura)", "preco": 300, "tipo": "moldura" },
  "389": { "nome": "Esmeralda Antiga (Moldura)", "preco": 300, "tipo": "moldura" },
  "390": { "nome": "Rubi Flamejante (Moldura)", "preco": 300, "tipo": "moldura" },
  "391": { "nome": "Safira de Gelo (Moldura)", "preco": 300, "tipo": "moldura" },
  "392": { "nome": "Diamante Brilhante (Moldura)", "preco": 300, "tipo": "moldura" },
  "393": { "nome": "Ametista Mística (Moldura)", "preco": 300, "tipo": "moldura" },
  "394": { "nome": "Obsidiana Negra (Moldura)", "preco": 300, "tipo": "moldura" },
  "395": { "nome": "Osso Antigo (Moldura)", "preco": 300, "tipo": "moldura" },
  "396": { "nome": "Teia de Aranha (Moldura)", "preco": 300, "tipo": "moldura" },
  "397": { "nome": "Vento Veloz (Moldura)", "preco": 300, "tipo": "moldura" },
  "398": { "nome": "Terra Firme (Moldura)", "preco": 300, "tipo": "moldura" },
  "399": { "nome": "Planta Carnívora (Moldura)", "preco": 300, "tipo": "moldura" },
  "400": { "nome": "Coração Apaixonado (Moldura)", "preco": 300, "tipo": "moldura" },
  "401": { "nome": "Estrela Cadente (Moldura)", "preco": 300, "tipo": "moldura" },
  "402": { "nome": "Lua Cheia (Moldura)", "preco": 300, "tipo": "moldura" },
  "403": { "nome": "Sol Radiante (Moldura)", "preco": 300, "tipo": "moldura" },
  "404": { "nome": "Nuvem Voadora (Moldura)", "preco": 300, "tipo": "moldura" },
  "405": { "nome": "Engrenagem Mecânica (Moldura)", "preco": 300, "tipo": "moldura" },
  "406": { "nome": "Asas de Fênix (Moldura)", "preco": 300, "tipo": "moldura" },
  "407": { "nome": "Escamas de Dragão (Moldura)", "preco": 300, "tipo": "moldura" },
  "408": { "nome": "Garras de Lobo (Moldura)", "preco": 300, "tipo": "moldura" },
  "409": { "nome": "Pena de Grifo (Moldura)", "preco": 300, "tipo": "moldura" },
  "410": { "nome": "Lágrima de Sereia (Moldura)", "preco": 300, "tipo": "moldura" },
  "411": { "nome": "Olho de Gato (Moldura)", "preco": 300, "tipo": "moldura" },
  "412": { "nome": "Moeda de Ouro (Moldura)", "preco": 300, "tipo": "moldura" },
  "413": { "nome": "Cálice Sagrado (Moldura)", "preco": 300, "tipo": "moldura" },
  "414": { "nome": "Espada Lendária (Moldura)", "preco": 300, "tipo": "moldura" },
  "415": { "nome": "Escudo Inabalável (Moldura)", "preco": 300, "tipo": "moldura" },
  "416": { "nome": "Arco Certeiro (Moldura)", "preco": 300, "tipo": "moldura" },
  "417": { "nome": "Cajado Mágico (Moldura)", "preco": 300, "tipo": "moldura" },
  "418": { "nome": "Livro de Feitiços (Moldura)", "preco": 300, "tipo": "moldura" },
  "419": { "nome": "Poção de Vida (Moldura)", "preco": 300, "tipo": "moldura" },
  "420": { "nome": "Poção de Mana (Moldura)", "preco": 300, "tipo": "moldura" },
  "421": { "nome": "Cristal de Energia (Moldura)", "preco": 300, "tipo": "moldura" },
  "422": { "nome": "Runa Antiga (Moldura)", "preco": 300, "tipo": "moldura" },
  "423": { "nome": "Pergaminho Sagrado (Moldura)", "preco": 300, "tipo": "moldura" },
  "424": { "nome": "Coroa Real (Moldura)", "preco": 300, "tipo": "moldura" },
  "425": { "nome": "Tridente dos Mares (Moldura)", "preco": 300, "tipo": "moldura" },
  "426": { "nome": "Foice da Morte (Moldura)", "preco": 300, "tipo": "moldura" },
  "427": { "nome": "Martelo de Thor (Moldura)", "preco": 300, "tipo": "moldura" },
  "428": { "nome": "Anel do Poder (Moldura)", "preco": 300, "tipo": "moldura" },
  "429": { "nome": "Bandeira de Guerra (Moldura)", "preco": 300, "tipo": "moldura" },
  "430": { "nome": "Taverna do RPG (Moldura)", "preco": 300, "tipo": "moldura" },
  "431": { "nome": "Aura de Partículas de Ouro", "preco": 1200, "tipo": "cosmetico" },
  "432": { "nome": "Pegadas Flamejantes", "preco": 1200, "tipo": "cosmetico" },
  "433": { "nome": "Asas de Anjo de Luz", "preco": 1200, "tipo": "cosmetico" },
  "434": { "nome": "Efeito de Voz Ecoante", "preco": 1200, "tipo": "cosmetico" },
  "435": { "nome": "Aura de Sombras da Noite", "preco": 1200, "tipo": "cosmetico" },
  "436": { "nome": "Pegadas de Gelo Eterno", "preco": 1200, "tipo": "cosmetico" },
  "437": { "nome": "Asas de Demônio de Fogo", "preco": 1200, "tipo": "cosmetico" },
  "438": { "nome": "Efeito de Brilho Estelar", "preco": 1200, "tipo": "cosmetico" },
  "439": { "nome": "Aura de Raios Elétricos", "preco": 1200, "tipo": "cosmetico" },
  "440": { "nome": "Pegadas de Folhas de Sakura", "preco": 1200, "tipo": "cosmetico" },
  "441": { "nome": "Asas de Fênix Ardente", "preco": 1200, "tipo": "cosmetico" },
  "442": { "nome": "Efeito de Névoa Mística", "preco": 1200, "tipo": "cosmetico" },
  "443": { "nome": "Aura de Folhas de Outono", "preco": 1200, "tipo": "cosmetico" },
  "444": { "nome": "Pegadas de Lama do Pântano", "preco": 1200, "tipo": "cosmetico" },
  "445": { "nome": "Asas de Borboleta Mágica", "preco": 1200, "tipo": "cosmetico" },
  "446": { "nome": "Efeito de Luz Divina", "preco": 1200, "tipo": "cosmetico" },
  "447": { "nome": "Aura de Bolhas de Água", "preco": 1200, "tipo": "cosmetico" },
  "448": { "nome": "Pegadas de Areia do Deserto", "preco": 1200, "tipo": "cosmetico" },
  "449": { "nome": "Asas de Morcego Sombrio", "preco": 1200, "tipo": "cosmetico" },
  "450": { "nome": "Efeito de Eco Fantasmagórico", "preco": 1200, "tipo": "cosmetico" },
  "451": { "nome": "Aura de Pétalas de Rosa", "preco": 1200, "tipo": "cosmetico" },
  "452": { "nome": "Pegadas de Sangue Vampírico", "preco": 1200, "tipo": "cosmetico" },
  "453": { "nome": "Asas de Fada Brilhante", "preco": 1200, "tipo": "cosmetico" },
  "454": { "nome": "Efeito de Escuridão Profunda", "preco": 1200, "tipo": "cosmetico" },
  "455": { "nome": "Aura de Engrenagens Steampunk", "preco": 1200, "tipo": "cosmetico" },
  "456": { "nome": "Pegadas de Faíscas Mecânicas", "preco": 1200, "tipo": "cosmetico" },
  "457": { "nome": "Asas Mecânicas de Ícaro", "preco": 1200, "tipo": "cosmetico" },
  "458": { "nome": "Efeito de Som Cyberpunk", "preco": 1200, "tipo": "cosmetico" },
  "459": { "nome": "Aura de Cristais de Mana", "preco": 1200, "tipo": "cosmetico" },
  "460": { "nome": "Pegadas de Luz Sagrada", "preco": 1200, "tipo": "cosmetico" },
  "461": { "nome": "Asas de Dragão Ancião", "preco": 1200, "tipo": "cosmetico" },
  "462": { "nome": "Efeito de Voz de Dragão", "preco": 1200, "tipo": "cosmetico" },
  "463": { "nome": "Aura de Moedas Flutuantes", "preco": 1200, "tipo": "cosmetico" },
  "464": { "nome": "Pegadas de Ouro Maciço", "preco": 1200, "tipo": "cosmetico" },
  "465": { "nome": "Asas de Anjo Caído", "preco": 1200, "tipo": "cosmetico" },
  "466": { "nome": "Efeito de Sussurro das Sombras", "preco": 1200, "tipo": "cosmetico" },
  "467": { "nome": "Aura de Espíritos Brcalhões", "preco": 1200, "tipo": "cosmetico" },
  "468": { "nome": "Pegadas de Fantasma Alado", "preco": 1200, "tipo": "cosmetico" },
  "469": { "nome": "Asas de Pixels Retro", "preco": 1200, "tipo": "cosmetico" },
  "470": { "nome": "Efeito de Glitch Digital", "preco": 1200, "tipo": "cosmetico" },
  "471": { "nome": "Aura de Fumaça Negra", "preco": 1200, "tipo": "cosmetico" },
  "472": { "nome": "Pegadas Tóxicas Verdes", "preco": 1200, "tipo": "cosmetico" },
  "473": { "nome": "Asas de Corvo da Morte", "preco": 1200, "tipo": "cosmetico" },
  "474": { "nome": "Efeito de Riso Macabro", "preco": 1200, "tipo": "cosmetico" },
  "475": { "nome": "Aura de Estrelas Cadentes", "preco": 1200, "tipo": "cosmetico" },
  "476": { "nome": "Pegadas Radiantes", "preco": 1200, "tipo": "cosmetico" },
  "477": { "nome": "Asas de Seda Celestial", "preco": 1200, "tipo": "cosmetico" },
  "478": { "nome": "Efeito de Melodia de Bardo", "preco": 1200, "tipo": "cosmetico" },
  "479": { "nome": "Aura de Runas Flutuantes", "preco": 1200, "tipo": "cosmetico" },
  "480": { "nome": "Pegadas rúnicas de Fogo", "preco": 1200, "tipo": "cosmetico" },
  "481": { "nome": "Asas de Gelo Glacial", "preco": 1200, "tipo": "cosmetico" },
  "482": { "nome": "Efeito de Rugido de Urso", "preco": 1200, "tipo": "cosmetico" },
  "483": { "nome": "Aura de Teias de Aranha", "preco": 1200, "tipo": "cosmetico" },
  "484": { "nome": "Pegadas de Veneno Roxo", "preco": 1200, "tipo": "cosmetico" },
  "485": { "nome": "Asas de Inseto Gigante", "preco": 1200, "tipo": "cosmetico" },
  "486": { "nome": "Efeito de Som de Tambores", "preco": 1200, "tipo": "cosmetico" },
  "487": { "nome": "Aura de Laser Cyber", "preco": 1200, "tipo": "cosmetico" },
  "488": { "nome": "Pegadas de Neon Fluorescente", "preco": 1200, "tipo": "cosmetico" },
  "489": { "nome": "Asas de Holograma Azul", "preco": 1200, "tipo": "cosmetico" },
  "490": { "nome": "Efeito de Alarme de Intrusão", "preco": 1200, "tipo": "cosmetico" },
  "491": { "nome": "Aura de Fogo Fátuo", "preco": 1200, "tipo": "cosmetico" },
  "492": { "nome": "Pegadas de Alma Penada", "preco": 1200, "tipo": "cosmetico" },
  "493": { "nome": "Asas de Luz de Neon", "preco": 1200, "tipo": "cosmetico" },
  "494": { "nome": "Efeito de Voz Metalizada", "preco": 1200, "tipo": "cosmetico" },
  "495": { "nome": "Aura Cósmica de Nebulosa", "preco": 1200, "tipo": "cosmetico" },
  "496": { "nome": "Pegadas de Poeira Estelar", "preco": 1200, "tipo": "cosmetico" },
  "497": { "nome": "Asas Cósmicas Roxas", "preco": 1200, "tipo": "cosmetico" },
  "498": { "nome": "Efeito de Silêncio do Vácuo", "preco": 1200, "tipo": "cosmetico" },
  "499": { "nome": "Aura de Arco-Íris Radiante", "preco": 1200, "tipo": "cosmetico" },
  "500": { "nome": "Pegadas Coloridas da Sorte", "preco": 1200, "tipo": "cosmetico" },
  "501": { "nome": "Asas de Algodão Doce", "preco": 1200, "tipo": "cosmetico" },
  "502": { "nome": "Efeito de Risada de Criança", "preco": 1200, "tipo": "cosmetico" }
};

export default {
  name: "loja",
  description: "Mostra as abas de itens do RPG",
  commands: ["loja", "shop"],
  usage: `${PREFIX}loja [categoria]`,

  handle: async ({ args, socket, remoteJid, userLid, sendErrorReply }) => {
    if (!isGroup(remoteJid)) return sendErrorReply("Este comando só pode ser usado em grupo.");

    // Normaliza a entrada removendo acentos para evitar erros com 'montarias', 'chapeus', etc.
    const categoria = args[0] ? args[0].toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "") : "";
    
    let bancoRPG = {};
    if (fs.existsSync(dbPath)) bancoRPG = JSON.parse(fs.readFileSync(dbPath, "utf-8"));
    const numeroLimpo = userLid.split("@")[0];
    
    const p = bancoRPG[numeroLimpo] || {};
    const saldo = p.ouro || 0;

    // Backups automáticos de coleções do jogador
    const racasCompradas = p.racasCompradas || [p.raca || "Humano"];
    const classesCompradas = p.classesCompradas || [p.classe || "Guerreiro"];
    const inventario = p.inventario || [];

    let textoLoja = `🛒 *LOJA THE LEGENDARY ONLINE* 🛒\n`;
    textoLoja += `💰 *Seu Saldo:* 🪙 ${saldo} moedas de ouro\n`;
    textoLoja += `─────────────────────────\n\n`;

    // Mapeador de cabeçalhos e tipos para deixar o código enxuto e dinâmico
    const mapeamentoAbas = {
      "raca": { tipo: "raca", titulo: "🧬 ABA DE RAÇAS", custoFixo: 250 },
      "racas": { tipo: "raca", titulo: "🧬 ABA DE RAÇAS", custoFixo: 250 },
      "classe": { tipo: "classe", titulo: "🛡️ ABA DE CLASSES", custoFixo: 200 },
      "classes": { tipo: "classe", titulo: "🛡️ ABA DE CLASSES", custoFixo: 200 },
      "titulo": { tipo: "titulo", titulo: "🏅 ABA DE TÍTULOS" },
      "titulos": { tipo: "titulo", titulo: "🏅 ABA DE TÍTULOS" },
      "montaria": { tipo: "montaria", titulo: "🐎 ABA DE MONTARIAS" },
      "montarias": { tipo: "montaria", titulo: "🐎 ABA DE MONTARIAS" },
      "chapeu": { tipo: "chapeu", titulo: "🎩 ABA DE CHAPÉUS" },
      "chapeus": { tipo: "chapeu", titulo: "🎩 ABA DE CHAPÉUS" },
      "acessorio": { tipo: "acessorio", titulo: "📿 ABA DE ACESSÓRIOS" },
      "acessorios": { tipo: "acessorio", titulo: "📿 ABA DE ACESSÓRIOS" },
      "moldura": { tipo: "moldura", titulo: "🖼️ ABA DE MOLDURAS" },
      "molduras": { tipo: "moldura", titulo: "🖼️ ABA DE MOLDURAS" },
      "cosmetico": { tipo: "cosmetico", titulo: "✨ ABA DE COSMÉTICOS" },
      "cosmeticos": { tipo: "cosmetico", titulo: "✨ ABA DE COSMÉTICOS" }
    };

    if (mapeamentoAbas[categoria]) {
      const aba = mapeamentoAbas[categoria];
      textoLoja += `*${aba.titulo}*\n\n`;

      for (const [id, item] of Object.entries(ITENS_LOJA)) {
        if (item.tipo === aba.tipo) {
          let jaTem = "";
          
          // Verificação de posse customizada baseada no tipo do item
          if (item.tipo === "raca") jaTem = racasCompradas.includes(item.nome) ? " ✅" : "";
          else if (item.tipo === "classe") jaTem = classesCompradas.includes(item.nome) ? " ✅" : "";
          else jaTem = inventario.includes(item.nome) ? " ✅" : "";

          textoLoja += `*🆔 [${id}]* - ${item.nome}${jaTem}\n• Preço: 🪙 ${item.preco} moedas\n\n`;
        }
      }
    } else {
      // Menu Principal da Loja (Caso o usuário digite apenas /loja)
      textoLoja += `📜 *CATEGORIAS DISPONÍVEIS*\n\n`;
      textoLoja += `🧬 \`${PREFIX}loja racas\` - Escolha sua linhagem\n`;
      textoLoja += `🛡️ \`${PREFIX}loja classes\` - Defina sua profissão de combate\n`;
      textoLoja += `🏅 \`${PREFIX}loja titulos\` - Títulos lendários para ostentar\n`;
      textoLoja += `🐎 \`${PREFIX}loja montarias\` - Criaturas e veículos mágicos\n`;
      textoLoja += `🎩 \`${PREFIX}loja chapeus\` - Capuzes, elmos e aparências de cabeça\n`;
      textoLoja += `📿 \`${PREFIX}loja acessorios\` - Anéis, colares e capas potentes\n`;
      textoLoja += `🖼️ \`${PREFIX}loja molduras\` - Bordas personalizadas para o seu perfil\n`;
      textoLoja += `✨ \`${PREFIX}loja cosmeticos\` - Auras e pegadas com efeitos místico\n`;
      textoLoja += `─────────────────────────\n`;
      textoLoja += `💡 *Exemplo:* Use \`${PREFIX}loja montarias\` para ver os animais disponíveis!`;
    }

    textoLoja += `\n\n🛒 Para comprar use: *${PREFIX}comprar [número]*`;

    await socket.sendMessage(remoteJid, { text: textoLoja });
  }
};
