// 🧬 BÔNUS PASSIVOS DAS 30 RAÇAS DO RPG
export const RACAS_RPG = {
  "Humano": { hpBonus: 0, danoBonus: 5, descrição: "Versátil e equilibrado em combates." },
  "Elfo": { hpBonus: 0, danoBonus: 3, criticoBonus: 10, descrição: "Alta precisão e agilidade." },
  "Oni (Demônio Oriental)": { hpBonus: 15, danoBonus: 5, descrição: "Força bruta demoníaca e resistência." },
  "Meio-Fera": { hpBonus: 5, danoBonus: 4, descrição: "Instintos aguçados e velocidade." },
  "Anão": { hpBonus: 25, danoBonus: 0, descrição: "Resistência massiva a golpes." },
  "Morto-Vivo": { hpBonus: 10, drenoBonus: 3, descrição: "Não sente dor e absorve energia vital." },
  "Vampiro": { hpBonus: 0, danoBonus: 6, drenoBonus: 4, descrição: "Causa dano alto e cura-se com o sangue." },
  "Anjo Caído": { hpBonus: 5, danoBonus: 7, descrição: "Poderes sombrios e celestiais combinados." },
  "Fada": { hpBonus: -10, curaBonus: 10, descrição: "Frágil, mas com alta capacidade mágica." },
  "Sereia / Tritão": { hpBonus: 10, escudoBonus: 5, descrição: "Domínio das águas e barreiras fluídas." },
  "Goblin": { hpBonus: -15, ouroBonus: 20, descrição: "Fraco em combate, mas ganha mais ouro por vitória." },
  "Orc": { hpBonus: 30, danoBonus: 2, descrição: "Pele espessa e fúria de combate." },
  "Ciborgue / Autômato": { hpBonus: 20, escudoBonus: 10, descrição: "Partes mecânicas que geram blindagem." },
  "Espírito / Fantasma": { hpBonus: 0, esquivaBonus: 15, descrição: "Incorpóreo, difícil de ser atingido." },
  "Draconato (Meio-Dragão)": { hpBonus: 15, danoBonus: 6, descrição: "Resistência elemental e sopro destrutivo." },
  "Elfo Negro (Drow)": { hpBonus: 0, danoBonus: 8, descrição: "Mestre das emboscadas e venenos." },
  "Slime Humanóide": { hpBonus: 35, danoBonus: -5, descrição: "Corpo maleável que absorve muito impacto." },
  "Metamorfo": { hpBonus: 5, danoBonus: 5, descrição: "Capacidade de se adaptar ao oponente." },
  "Titã (Gigante)": { hpBonus: 50, danoBonus: 10, descrição: "Tamanho colossal, vida gigantesca, mas lento." },
  "Ser Estelar": { hpBonus: 10, danoBonus: 10, descrição: "Poder cósmico puro vindo do espaço." },
  "Centauro": { hpBonus: 15, danoBonus: 5, descrição: "Velocidade de galope e coices potentes." },
  "Minotauro": { hpBonus: 25, danoBonus: 7, descrição: "Força de carga implacável e fúria de labirinto." },
  "Lobisomem": { hpBonus: 20, danoBonus: 8, descrição: "Garras afiadas que dilaceram sob a lua cheia." },
  "Nefalim": { hpBonus: 15, danoBonus: 8, descrição: "Híbrido de anjo e demônio com poder destrutivo." },
  "Kitsune": { hpBonus: 5, esquivaBonus: 10, descrição: "Raposa mística de nove caudas com magia ilusória." },
  "Lizardfolk (Homem-Lagarto)": { hpBonus: 20, escudoBonus: 5, descrição: "Escamas rígidas e regeneração natural de réptil." },
  "Gárgula": { hpBonus: 30, escudoBonus: 10, descrição: "Pele de pedra que bloqueia a maioria dos ataques." },
  "Sylph (Espírito do Ar)": { hpBonus: 0, esquivaBonus: 15, descrição: "Leve como a brisa, extremamente difícil de golpear." },
  "Undine (Espírito da Água)": { hpBonus: 10, curaBonus: 8, descrição: "Magia fluida que cura ferimentos rapidamente." },
  "Salamandra (Espírito do Fogo)": { hpBonus: 5, danoBonus: 10, descrição: "Coração ardente que queima os inimigos com calor intenso." }
};
